title: Website van Vicca
author: Victor Laforga
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  2de jaars student op de HvA!

# social links
twitter_username: No twitter
github_username:  victorlaforga

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
